### PR TITLE
TSK-2750 Create and update demo on startup and states

### PR DESCRIPTION
**Pull request by bmort**
## Description:
Created standalone demo, based on Nov 18 prototyping demo meeting, which introduces:

1. how SIP SDP services are started using a Docker Swarm stack deployment 
2. how the overall state of SDP can be queried and set using Tango attributes on the SDP Tango Master device.

To make this possible some minor refactoring of the EC Master Controller and Alarms service was also carried out. Finally, this branch also renames the old November demos folder for better naming consistency.

## Testing instructions:
See `README.md` in the `demos/01_sdp_states` folder.

## Types of changes
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] The code follows the code style of this project.
- [ ] The changes require a documentation update.
- [x] Documentation has been updated accordingly.
- [ ] Tests cover all changes in this PR.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by david-terrett** [comment]
Ben,

I’ve added a tiny suggestion to the comments in the ticket. If you can add that to the readme I will approve the request.

How do you want to handle issues discovered when going “off-piste”. I have two already! Do you want a ticket for each one? One mega-ticket or what?

David

**Comment by bmort** [comment]
I've updated the readme with the suggestions from the ticket. 

For issues identified by going off script, perhaps add them as a comment to TSK-2750 for now or alternatively add them as GitHub issues. We can then discuss them as a group in one of the next SIP telescons to work out how to convert them into tickets to fix the code. My preferred solution for this is to create a single story for the fixes needed but depending on how much work it looks like being we might want to revise that!

**Comment by bmort** [comment]
Thanks for approving this, I'll Squash and merge in a min when the travis CI build has finished.

**Comment by david-terrett** [comment]
Going from standby to disabled causes the master controller to exit with a critical error.

https://github.com/SKA-ScienceDataProcessor/integration-prototype/issues/91

**Pull request merged**
