### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by bmort**
This is the revised logging API for SIP. 

This is a pretty involved change that touches quite a lot of files so a summary of the main changes is as follows:

- I've replaced the existing logging functions in sip_common/ with 4 new files: 
  - `logging_api.py`: Provides the log object used by sip modules and two classes, SipLogRecord and SipLogger. These override the Python logging.Logger class with a custom LogRecord type with additional meta-data.
  - `logging_handlers.py`: Provides a couple of logging handlers (and formatters) for ZMQ and STDOUT log messages.
  - `logging_aggregator.py`: Contains a logging subscription class for reconstructing log messages sent over ZMQ. Messages are received from the ZMQ Log handler which sends JSON encoded log records, then reconstructed as Python LogRecords before being written to STDOUT with a custom formatter.
  - `logging_server.py`: Contains a main() function using the logging aggregator to provide a logging service for SIP.

- In order to use the new logging API a lot of files have been updated to the new functions.
- I've added two unit tests
  - `common/test/test_zmq_pub_sub.py` testing ZMQ PUB-SUB behaviour
  - `common/test/test_logging.py` with a basic test of the new logging API.
  - these can be run from the top level SIP directory with the commands:
```
   $ python3 -m unittest common.test.test_zmq_pub_sub
   $ python3 -m unittest common.test.test_logging
```
- I've updated the Sphinx API doc to include the new logging function documentation
- I've also included a number of other minor tweaks to the code to improve PEP standard compliance where I found issues while updating the logging code.

I hope this is not too much of a nightmare to look though. If you have any questions or what to have a quick telecon for me to go over the changes in more detail let me know. If something doesn't make sense or doesnt work as expected also let me know and i'll fix it ASAP.

### CODE REVIEW

**Comment by njthykkathu** [comment]
Hi,

When I try to enable SIP to online state , I get the following error message

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/njthykkathu/integration-prototype/common/sip_common/logging_aggregator.py", line 78, in run
    values = json.loads(values.decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Terminating Logging Aggregator service (pid: 3351).

**Comment by bmort** [comment]
It looks like there is a problem decoding the JSON log record values. I've not yet been able to reproduce the problem on my system so i've added a couple of new checks in the receive loop which should help diagnose the problem. Its possible something isn't being serialised correctly on the sender side but that is hard to figure out without being able to reproduce the error.

**Comment by njthykkathu** [comment]
With the latest update, I can see that there is  a problem with converting the JSON log record

ERROR: Unable to convert JSON log record:
------------------------------------------------------------
b'Starting task /home/sdp/integration-prototype/tasks/task.py\n'
------------------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/njthykkathu/integration-prototype/common/sip_common/logging_aggregator.py", line 83, in run
    dict_values = json.loads(str_values)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Terminating Logging Aggregator service (pid: 4862).

**Comment by bmort** [comment]
Thanks for that, I can see why that didn't work. There is a non JSONified log message being sent somewhere. I'll see if I can track it down and push another update.

**Comment by bmort** [comment]
Up to the point where you get the error, does you log output look something like this?

[https://gist.github.com/bmort/fc56f8790477ff1758aac8d839318f70](https://gist.github.com/bmort/fc56f8790477ff1758aac8d839318f70)

**Comment by bmort** [comment]
I've pushed in a quick modification to the log messages related to starting tasks to see if it is possible to narrow down exactly where the problem is coming from. When you get time, could you run this new code and post the error string again.

**Comment by njthykkathu** [comment]
My output looks like this

[sip_stdout.txt](https://github.com/SKA-ScienceDataProcessor/integration-prototype/files/739299/sip_stdout.txt)

**Comment by njthykkathu** [comment]
Following shows the output I get with the new changes. it outputs the error before I go online

[Output_with_change.txt](https://github.com/SKA-ScienceDataProcessor/integration-prototype/files/739305/Output_with_change.txt)

**Comment by bmort** [comment]
Hi, 

I've finally managed to get around to cleaning up the debug statements which I added yesterday. I've also updated the logger to use the 'SIP_HOSTNAME' variable again (I mentioned this morning the pervious version was hardcoded to '127.0.0.1') which should mean the logger works properly if the logging server isn't being run on localhost. 

To test the code, you'll have to update the slave_controller Docker image again with the command:

```
docker build -f slave/Dockerfile -t slave_controller .
```
as I fixed a missing dependency in the docker file.

Hopefully this time the code should work!

Cheers,
Ben.

**Comment by njthykkathu** [comment]
Hi,

I can confirm that I can now run the new logging api and it is successfully running on my system. I have changed the import for pulsar_search capability and the messages do get outputted onto the terminal.

Only minor point I found was the logging_api import in vis_receiver_task.py is incorrect.

**Pull request merged**
