### PR TITLE
Mc rest

### PR DESCRIPTION
**Pull request by apmcd42**
This is the latest version of my code in the MC_REST branch. I have added code from directory configuration_db/redis/db_client from the feature/configuration_db simply to get the latest code.
The start_master_controller_service script copies this code into the app directories of the master_controller_service and master_interface_service as a stop-gap until we use Nijin's code in a python package.
Instructions to run these services can be found in the appropriate sub-directory (master_interface_service/rest and master_controller_service)

### CODE REVIEW

**Comment by njthykkathu** [comment]
I had quick look through the code. I have a couple of suggestions, 

1. I think it might be good to put all the scripts under master_controller directory and have a README file at that level which gives instructions on how to run the controller and interface.
2. There are some pylint/pydocstyle errors shown in Travis, have a look at them and resolve as much as you can.

**Comment by njthykkathu** [comment]
I have reviewed the pull request. 
The system works great. There are some minor issues that need to look into:

- It might be a good idea to merge the README files. One for master_interface_service and one for master_controller_service
- We no longer need the init_db.py script as it belongs to the previous master_controller.

**Comment by njthykkathu** [comment]
I have made some very minor changes to the branch

- I don’t think we need the service_watchdog directory anymore, therefore, I deleted it.
- Travis reported some errors and I have updated them.

**Comment by apmcd42** [comment]
Merging the Master Interface Service (REST variant) and the Master Controller Service into the main codebase.

**Comment by apmcd42** [comment]
Merging the Master Interface Service (REST variant) and the Master Controller Service into the main codebase. (attempt 2)

**Pull request merged**
